### ISSUE TITLE
Stack failing to deploy because of existing cloudtrail s3 bucket

### ISSUE THREAD

**Issue by fitchtravis** [virtualjj/cis-aws-foundations-cloudformation#1]
Hi there,

When I am deploying cis-aws-benchmark-section-2-monitoring-remediate stack, it fails because the S3 bucket already exisits for Cloudtrail. 

It seems that the CF stack wants to create a new bucket. 

CREATE_FAILED | AWS::S3::Bucket | CloudTrailS3Bucket | cloudtrail-xyxyxyx already exists

What needs to be modified to cater for a bucket that is already used for centralised cloudtrail logs in a different account?

Regards,

Travis

**Comment by virtualjj** [comment]
Travis,

Thanks for trying out my template!

My understanding is that you want this template to use an S3 bucket that is located in a different AWS account, correct?

If so, I think you'll have to do that using [CloudFormation StackSets](https://aws.amazon.com/blogs/aws/use-cloudformation-stacksets-to-provision-resources-across-multiple-aws-accounts-and-regions/) which let's you create resources across multiple AWS accounts.

I'll try testing and updating this template to work across multiple accounts but I'm not sure when I'll be able to get started. It actually makes sense to have this work for multiple accounts that use a centralized bucket which is/should be a common use case. Thanks for bringing this up!

**Comment by Pl4nky** [comment]
Can confirm the behavior initially reported. If I deploy this CF template, entering a existing bucket name that resides in the same account causes the deployment to fail with the message that the S3 bucket already exists.

**Comment by virtualjj** [comment]
This should be fixed - please confirm!

**Comment by Pl4nky** [comment]
Tested by deploying without a bucketname specified and specifying an existing bucket - both worked without issue. Thanks!
