### ISSUE TITLE
Cannot customise role name

### ISSUE THREAD

**Issue by Pl4nky** [virtualjj/cis-aws-foundations-cloudformation#2]
I am attempting to deploy this CF template with "IAM-DPT-INF-ACCNAME-R-CIS-Benchmark" or even just "test" as the role name, however it fails with the following error:

> Template validation error: Parameter NameCloudTrailRole failed to satisfy constraint: The role name must contain only upper and lowercase alphanumeric characters with no spaces. These characters are alllowed: = , . @ -

As far as I can see this matches the requirements?  I suspect the regex pattern is incorrect (but I have no clue how to decipher them)...

**Comment by virtualjj** [comment]
Thanks for trying out my template and pointing this issue out! I just fixed the issue:

![image](https://user-images.githubusercontent.com/10323889/39735434-848dd494-52b6-11e8-99a8-8224a793ca25.png)

![image](https://user-images.githubusercontent.com/10323889/39735448-96326728-52b6-11e8-916b-0e1282e0f890.png)

It's been a while since I've worked on this so it's probably time to work on it some more. :(

When you get a chance, please confirm that the fix works - thanks in advance!

**Comment by Pl4nky** [comment]
Great! I'll test it

**Comment by Pl4nky** [comment]
Ran more or less successfully, I noted that the role name in the stack overview wasn't displayed.

In the outputs, it shows the region name has been prepended to the role name which isnt ideal:

> TrailLogGroupRole | ap-southeast-2-IAM-DPT-INF-ACCNAME-R-CIS-Benchmark | AWS::IAM::Role | CREATE_COMPLETE

Edit:

I see that the code checks if the role name value is empty/null it will append the region to a random name, but in this case the role name value isn't empty...

**Comment by virtualjj** [comment]
Okay, I have a fix for this but I'm also working on #1 as well. Swamped with some other things right now but will try to take care of this as soon as I can. Sorry for the inconvenience!

**Comment by virtualjj** [comment]
I have fixed this - please check when you get a chance. 

![image](https://user-images.githubusercontent.com/10323889/39772045-18092606-532f-11e8-94ec-8213a78d8790.png)

![image](https://user-images.githubusercontent.com/10323889/39772052-1d6923f8-532f-11e8-9172-3e23d8576a58.png)

**Comment by Pl4nky** [comment]
Thanks, that seems to be sorted now. 

I've been using this template for the better part of 6 months, appreciate the work that you've put into this template so we didnt have to.
